name: "Build (Java)"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  release:
    types: [ released, prereleased ]

jobs:
  build:
    uses: xpdustry/.github/.github/workflows/build-java.yaml@master
    with:
      java_version: 17
      gradle_build_tasks: "build release"
      gradle_artifacts_path: build/tmp/release/*.jar
      gradle_publish: false
    secrets: "inherit"
