name: "Build (Java)"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  workflow_dispatch:
    release:
      description: "Publish the project and increment version."
      type: boolean
      required: false
      default: false

jobs:
  build:
    uses: xpdustry/.github/.github/workflows/build-java.yaml@master
    with:
      java_version: 17
      gradle_build_tasks: "build release"
      gradle_publish: false
      artifacts_path: build/tmp/release/*.jar
    secrets: "inherit"
